### PR TITLE
Suggestion Refactoring, Bug Fixed and Some Layout and Styling aligned 

### LINKED ISSUE #363: In Suggestions, make the code cleaner
in Suggestions, make the code cleaner & comment on code, and reduce the complexity.

### PR DESCRIPTION
**Pull request by annhit29**
In this pull request,
**I mainly modularized and refactored code for Suggestions:**
To reduce the code complexity.
Almost every file has been refactored. The code is thus much cleaner. I have also commented on the code.

Additionally,
**I have fixed some bugs found:**
- in SuggestionItem: the countdown now continues counting down even if we go to other pages and even if we relaunch it
- in SuggestionItem: when the countdown reaches "00:00:00", we can no longer vote for a suggestion item by making its "Up" icon semi-transparent and non-clickable.

**Other Layout and Styling found that should also be aligned with other screens of the app:**
- suggestionHistoryItem shadow effect w/ ElevatedCard; suggestionHistoryList same spacing as in suggestionList
- suggestionDetail same topbar with the use of generic composable GoBackSuggestionTopBar applicable for all the topbars that need a `goBackButton` and a title, so have the same color as in anywhere else now; suggestionDetail same spacing between topbar and content as in suggestionList

This pull request is for issue #363 .

### CODE REVIEW

File: app/src/main/java/com/github/se/wanderpals/ui/screens/trip/Trip.kt
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/trip/Trip.kt:1]: Nice to remove parameters that can be stored elsewhere

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionTopBarWithHistory.kt
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionTopBarWithHistory.kt:1]: I don't find the change of name necessary

File: app/src/main/java/com/github/se/wanderpals/model/viewmodel/SuggestionsViewModel.kt
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/model/viewmodel/SuggestionsViewModel.kt:1]: Nice comments

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/BottomSheetOptions.kt
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/BottomSheetOptions.kt:1]: Very clean modularization

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/ConfirmDeleteDialog.kt [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+ *
+ * @param onDismissRequest The callback to be invoked when the dialog is dismissed.
+ * @param onConfirm The callback to be invoked when the user confirms the deletion.
+ * @param modifier The modifier to be applied to the dialog.
+ * @param confirmTestTag The test tag for the confirm button.
+ * @param cancelTestTag The test tag for the cancel button.
+ * @param dialogTestTag The test tag for the dialog.
+ */
+@Composable
+fun ConfirmDeleteDialog(
```
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/ConfirmDeleteDialog.kt:23]: Putting test tags as parameters is something that I haven't seen but it makes a lot of sense. Great job

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionDetail.kt [hunk 2]
```diff
@@ -359,3 +309,35 @@ private fun onDone(
...
+ * DetailRow composable function to display the details of a suggestion.
+ *
+ * @param icon The icon to display.
+ * @param contentDescription The content description of the icon.
+ * @param text The text to display.
+ * @param color The color of the text.
+ * @param testTag The test tag of the text.
+ */
+@Composable
+fun DetailRow(
```
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionDetail.kt:323]: Since it's only used in this file, I'm completely fine leaving it inside of this file. Otherwise, it should have been moved to a separete one

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionFeedContent.kt [hunk 3]
```diff
@@ -172,3 +126,42 @@ fun SuggestionFeedContent(
...
+ * Composable function to display the list of suggestions.
+ *
+ * @param suggestions The list of suggestions to be displayed.
+ * @param suggestionsViewModel The ViewModel for managing suggestions.
+ * @param navigationActions The navigation actions used to navigate to different screens.
+ * @param modifier The modifier for the list.
+ * @param testTag The test tag for the list.
+ */
+@Composable
+fun SuggestionList(
```
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionFeedContent.kt:140]: Same as DetailRow

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionHistoryItem.kt
Comment (mtv47) [inline app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionHistoryItem.kt:1]: Code is a lot more compact, great job!

**Review by mtv47 — APPROVED** [review]
It's a very big refactor, but the code became a lot more readable. Excellent work

**Comment by annhit29** [comment]
Thank you for the review!

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionTopBarWithHistory.kt
Comment (annhit29) [reply app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionTopBarWithHistory.kt:1]: The change of name from `SuggestionTopBar()` to `SuggestionTopBarWithHistory()` is for indicating that the Suggestion screen has a top bar with the title and the history button, unlike `GoBackSuggestionTopBar()` which is a generic function used for any top bar that has a go-back arrow button and a title for the top bar.

Changing the name of this composable gives programmers already an idea of what it will display when we see both `SuggestionTopBarWithHistory()` and `GoBackSuggestionTopBar()`.

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/ConfirmDeleteDialog.kt (hunk 1 above)
Comment (annhit29) [reply app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/ConfirmDeleteDialog.kt:23]: Thank you!

File: app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionHistoryItem.kt
Comment (annhit29) [reply app/src/main/java/com/github/se/wanderpals/ui/screens/suggestion/SuggestionHistoryItem.kt:1]: Thank you very much!
